# Generated by Django 4.1.3 on 2022-11-13 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='territorio',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
